using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rapid_e4473.Models;

namespace Rapid_e4473.HelperClasses
{
    public class ListVals
    {
        public static IEnumerable<_2_Address> addrs_states = new List<_2_Address> {
            new _2_Address {STATE = ""},
            new _2_Address {STATE = "AL"},
            new _2_Address {STATE = "AK"},
            new _2_Address {STATE = "AZ"},
            new _2_Address {STATE = "AR"},
            new _2_Address {STATE = "CA"},
            new _2_Address {STATE = "CO"},
            new _2_Address {STATE = "CT"},
            new _2_Address {STATE = "DE"},
            new _2_Address {STATE = "FL"},
            new _2_Address {STATE = "GA"},
            new _2_Address {STATE = "HI"},
            new _2_Address {STATE = "ID"},
            new _2_Address {STATE = "IL"},
            new _2_Address {STATE = "IN"},
            new _2_Address {STATE = "IA"},
            new _2_Address {STATE = "KS"},
            new _2_Address {STATE = "KY"},
            new _2_Address {STATE = "LA"},
            new _2_Address {STATE = "ME"},
            new _2_Address {STATE = "MD"},
            new _2_Address {STATE = "MA"},
            new _2_Address {STATE = "MI"},
            new _2_Address {STATE = "MN"},
            new _2_Address {STATE = "MS"},
            new _2_Address {STATE = "MO"},
            new _2_Address {STATE = "MT"},
            new _2_Address {STATE = "NE"},
            new _2_Address {STATE = "NV"},
            new _2_Address {STATE = "NH"},
            new _2_Address {STATE = "NJ"},
            new _2_Address {STATE = "NM"},
            new _2_Address {STATE = "NY"},
            new _2_Address {STATE = "NC"},
            new _2_Address {STATE = "ND"},
            new _2_Address {STATE = "OH"},
            new _2_Address {STATE = "OK"},
            new _2_Address {STATE = "OR"},
            new _2_Address {STATE = "PA"},
            new _2_Address {STATE = "RI"},
            new _2_Address {STATE = "SC"},
            new _2_Address {STATE = "SD"},
            new _2_Address {STATE = "TN"},
            new _2_Address {STATE = "TX"},
            new _2_Address {STATE = "UT"},
            new _2_Address {STATE = "VT"},
            new _2_Address {STATE = "VA"},
            new _2_Address {STATE = "WA"},
            new _2_Address {STATE = "WV"},
            new _2_Address {STATE = "WI"},
            new _2_Address {STATE = "WY"}
        };

        public static IEnumerable<_3b_Place_of_Birth> birth_states = new List<_3b_Place_of_Birth> {
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = ""},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "AL"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "AK"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "AZ"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "AR"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "CA"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "CO"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "CT"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "DE"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "FL"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "GA"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "HI"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "ID"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "IL"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "IN"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "IA"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "KS"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "KY"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "LA"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "ME"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "MD"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "MA"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "MI"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "MN"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "MS"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "MO"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "MT"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "NE"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "NV"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "NH"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "NJ"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "NM"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "NY"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "NC"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "ND"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "OH"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "OK"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "OR"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "PA"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "RI"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "SC"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "SD"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "TN"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "TX"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "UT"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "VT"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "VA"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "WA"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "WV"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "WI"},
            new _3b_Place_of_Birth {PLACE_OF_BIRTH_STATE = "WY"}
        };
         
        public static IEnumerable<_13_State_of_Residence> states = new List<_13_State_of_Residence> {
            new _13_State_of_Residence {RESIDENCE_STATE = ""},
            new _13_State_of_Residence {RESIDENCE_STATE = "AL"},
            new _13_State_of_Residence {RESIDENCE_STATE = "AK"},
            new _13_State_of_Residence {RESIDENCE_STATE = "AZ"},
            new _13_State_of_Residence {RESIDENCE_STATE = "AR"},
            new _13_State_of_Residence {RESIDENCE_STATE = "CA"},
            new _13_State_of_Residence {RESIDENCE_STATE = "CO"},
            new _13_State_of_Residence {RESIDENCE_STATE = "CT"},
            new _13_State_of_Residence {RESIDENCE_STATE = "DE"},
            new _13_State_of_Residence {RESIDENCE_STATE = "FL"},
            new _13_State_of_Residence {RESIDENCE_STATE = "GA"},
            new _13_State_of_Residence {RESIDENCE_STATE = "HI"},
            new _13_State_of_Residence {RESIDENCE_STATE = "ID"},
            new _13_State_of_Residence {RESIDENCE_STATE = "IL"},
            new _13_State_of_Residence {RESIDENCE_STATE = "IN"},
            new _13_State_of_Residence {RESIDENCE_STATE = "IA"},
            new _13_State_of_Residence {RESIDENCE_STATE = "KS"},
            new _13_State_of_Residence {RESIDENCE_STATE = "KY"},
            new _13_State_of_Residence {RESIDENCE_STATE = "LA"},
            new _13_State_of_Residence {RESIDENCE_STATE = "ME"},
            new _13_State_of_Residence {RESIDENCE_STATE = "MD"},
            new _13_State_of_Residence {RESIDENCE_STATE = "MA"},
            new _13_State_of_Residence {RESIDENCE_STATE = "MI"},
            new _13_State_of_Residence {RESIDENCE_STATE = "MN"},
            new _13_State_of_Residence {RESIDENCE_STATE = "MS"},
            new _13_State_of_Residence {RESIDENCE_STATE = "MO"},
            new _13_State_of_Residence {RESIDENCE_STATE = "MT"},
            new _13_State_of_Residence {RESIDENCE_STATE = "NE"},
            new _13_State_of_Residence {RESIDENCE_STATE = "NV"},
            new _13_State_of_Residence {RESIDENCE_STATE = "NH"},
            new _13_State_of_Residence {RESIDENCE_STATE = "NJ"},
            new _13_State_of_Residence {RESIDENCE_STATE = "NM"},
            new _13_State_of_Residence {RESIDENCE_STATE = "NY"},
            new _13_State_of_Residence {RESIDENCE_STATE = "NC"},
            new _13_State_of_Residence {RESIDENCE_STATE = "ND"},
            new _13_State_of_Residence {RESIDENCE_STATE = "OH"},
            new _13_State_of_Residence {RESIDENCE_STATE = "OK"},
            new _13_State_of_Residence {RESIDENCE_STATE = "OR"},
            new _13_State_of_Residence {RESIDENCE_STATE = "PA"},
            new _13_State_of_Residence {RESIDENCE_STATE = "RI"},
            new _13_State_of_Residence {RESIDENCE_STATE = "SC"},
            new _13_State_of_Residence {RESIDENCE_STATE = "SD"},
            new _13_State_of_Residence {RESIDENCE_STATE = "TN"},
            new _13_State_of_Residence {RESIDENCE_STATE = "TX"},
            new _13_State_of_Residence {RESIDENCE_STATE = "UT"},
            new _13_State_of_Residence {RESIDENCE_STATE = "VT"},
            new _13_State_of_Residence {RESIDENCE_STATE = "VA"},
            new _13_State_of_Residence {RESIDENCE_STATE = "WA"},
            new _13_State_of_Residence {RESIDENCE_STATE = "WV"},
            new _13_State_of_Residence {RESIDENCE_STATE = "WI"},
            new _13_State_of_Residence {RESIDENCE_STATE = "WY"}
        };
    }
}