<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="DashBoard.aspx.vb" Inherits="RapidInventoryWebApp.DashBoard" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head  runat="server">
    <link href="CSS/Styles.css" rel="stylesheet" />
    <title>Rapid Physical Count - Dashboard </title>
    <link href="StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="dashboard" runat="server">
    <table>
    <tr>
        <td>
             <div class="dashboardItem">
                 <div class="dashboardItemHeader">Counts</div>
                 <div id="counts" class="dashboardCountItemBody">
                     <asp:Label ID="lblCounts" runat="server" Text="12"></asp:Label>
                 </div>
             </div>
        </td>
        <td>
            <div class="dashboardItem">
                <div class="dashboardItemHeader">Non Validated Counts</div>
                <div class="dashboardItemBody">
                    <asp:GridView ID="gridNonValidCounts" runat="server" AllowSorting="True" CssClass="gridView">
                    </asp:GridView>

                </div>
             </div>
        </td>
    </tr>
        <tr>
            <td colspan="2">
                <div class="dashboardItem">
                <div class="dashboardItemHeader">Section Counts</div>
                <div class="dashboardItemBody">
                    <asp:GridView ID="gridSectionsCounted" runat="server" AllowSorting="True" CssClass="gridView" AutoGenerateDeleteButton="True">
                        <Columns>
                            <asp:buttonfield buttontype="Button" commandname="Edit" headertext="Edit" text="Edit">
                            <ControlStyle CssClass="button" />
                            </asp:buttonfield>
                            <asp:buttonfield buttontype="Button" commandname="ChangeSectionNumber" headertext="Change Section #" text="Change">
                            <ControlStyle CssClass="button" />
                            </asp:buttonfield>
                        </Columns>
                    </asp:GridView>
                    </div>
                </div>
            </td>
        </tr>
        </table>
        <div >
            <asp:Button ID="btnRefresh" runat="server" Text="Refresh" CssClass="button"/>
            <div>
                <asp:Label ID="lblLastRefreshed" runat="server" Text=""></asp:Label>
            </div>
            
        </div>
    </form>
    </body>
</html>
