'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace RapidInventoryWebApp

    Partial Public Class DashBoard

        '''<summary>
        '''dashboard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dashboard As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lblCounts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCounts As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''gridNonValidCounts control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gridNonValidCounts As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''gridSectionsCounted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gridSectionsCounted As Global.System.Web.UI.WebControls.GridView

        '''<summary>
        '''btnRefresh control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.Button

        '''<summary>
        '''lblLastRefreshed control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLastRefreshed As Global.System.Web.UI.WebControls.Label
    End Class
End Namespace
