<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="DeleteCount.aspx.vb" Inherits="RapidInventoryWebApp.DeleteCount" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="CSS/Styles.css" rel="stylesheet" />
</head>
<body>
    <form id="dashboard" runat="server">
        <div class="dashboardItem">
            <div class="dashboardItemHeader">Delete Count (sysadmin)</div>
            <div class="dashboardItemBody">
        <div>
            <asp:GridView ID="gridDeleteCount" runat="server" AutoGenerateDeleteButton="True"></asp:GridView>
        </div>
                </div>
            </div>
    </form>
</body>
</html>
