'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace RapidInventoryWebApp

    Partial Public Class DeleteCount

        '''<summary>
        '''dashboard control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dashboard As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''gridDeleteCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gridDeleteCount As Global.System.Web.UI.WebControls.GridView
    End Class
End Namespace
