<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="EditSection.aspx.vb" Inherits="RapidInventroyWebApp.EditSection1" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <link href="CSS/Styles.css" rel="stylesheet" />
</head>
<body>
    <form id="dashboard" runat="server">
        <div class="dashboardItem">
                <div class="dashboardItemHeader">Edit Section Number</div>
                <div class="dashboardItemBody">
            <asp:GridView ID="gridSectionScans" runat="server" AllowSorting="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"></asp:GridView>
                    </div>
            </div>
    </form>
</body>
</html>
