//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.Rapid_e4473.Rapid_e4473.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int CUST_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string ADDRS_1 { get; set; }
        public string ADDRS_2 { get; set; }
        public string CITY { get; set; }
        public string COUNTY { get; set; }
        public string STATE { get; set; }
        public string ZIP_COD { get; set; }
        public string PLACE_OF_BIRTH_FOREIGN { get; set; }
        public string WEIGHT { get; set; }
        public string GENDER { get; set; }
        public string BIRTHDATE { get; set; }
        public string SOC_SEC_NUM { get; set; }
        public string UPIN { get; set; }
        public string ETHNICITY { get; set; }
        public string RACE { get; set; }
        public string C11A { get; set; }
        public string C11B { get; set; }
        public string C11C { get; set; }
        public string C11D { get; set; }
        public string C11E { get; set; }
        public string C11F { get; set; }
        public string C11G { get; set; }
        public string C11H { get; set; }
        public string C11I { get; set; }
        public string C11J { get; set; }
        public string C11K { get; set; }
        public string C11L { get; set; }
        public string ALIEN { get; set; }
        public string RESIDENCE_STATE { get; set; }
        public string CITIZENSHIP { get; set; }
        public string ALIEN_NUM { get; set; }
        public string BARCODE { get; set; }
        public string EMAIL { get; set; }
        public string HEIGHT_FT { get; set; }
        public string HEIGHT_IN { get; set; }
        public string PLACE_OF_BIRTH_STATE { get; set; }
        public string PLACE_OF_BIRTH_CITY { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
    }
}
